import type { PRReviewFinding, PRReviewReport } from '@project-x/types';

export type PrFindingDisposition = 'reviewed' | 'ignored';

export type PrFindingDispositionMap = Readonly<Record<string, PrFindingDisposition>>;

export type FormatPrReviewMarkdownOptions = {
  /** Session-only finding dispositions. */
  dispositions?: PrFindingDispositionMap;
  /**
   * @deprecated Prefer `dispositions`. Treated as `reviewed`.
   */
  resolvedIds?: ReadonlySet<string>;
  /** Include a short handoff blurb at the top. */
  includeHandoffSummary?: boolean;
};

function severityLabel(severity: PRReviewFinding['severity']): string {
  return severity.toUpperCase();
}

export function resolveDispositionMap(
  dispositions?: PrFindingDispositionMap,
  resolvedIds?: ReadonlySet<string>,
): PrFindingDispositionMap {
  if (dispositions && Object.keys(dispositions).length > 0) {
    return dispositions;
  }
  if (!resolvedIds || resolvedIds.size === 0) {
    return {};
  }
  const mapped: Record<string, PrFindingDisposition> = {};
  for (const id of resolvedIds) {
    mapped[id] = 'reviewed';
  }
  return mapped;
}

function statusLabel(
  findingId: string,
  dispositions: PrFindingDispositionMap,
): 'open' | 'reviewed' | 'ignored' {
  return dispositions[findingId] ?? 'open';
}

function formatFinding(finding: PRReviewFinding, dispositions: PrFindingDispositionMap): string {
  const status = statusLabel(finding.id, dispositions);
  const path = finding.filePath ? `\`${finding.filePath}\`` : '_unspecified file_';
  const why = finding.why ? `\n   Why: ${finding.why}` : '';
  return `${finding.index}. **[${severityLabel(finding.severity)}]** ${path} — ${finding.title} (${status})${why}`;
}

/**
 * Client-side review handoff summary (no extra model call).
 */
export function buildPrReviewHandoffSummary(
  report: PRReviewReport,
  dispositions: PrFindingDispositionMap = {},
): string {
  let open = 0;
  let reviewed = 0;
  let ignored = 0;
  for (const finding of report.findings) {
    const status = dispositions[finding.id];
    if (status === 'reviewed') {
      reviewed += 1;
    } else if (status === 'ignored') {
      ignored += 1;
    } else {
      open += 1;
    }
  }

  const prLabel = report.pullRequest.title
    ? `#${report.pullRequest.number} ${report.pullRequest.title}`
    : `#${report.pullRequest.number}`;

  return [
    `PR ${prLabel} in ${report.repository.owner}/${report.repository.name}`,
    `Overall risk: ${report.riskLevel.toUpperCase()}`,
    `Findings: ${report.stats.findings} total · ${report.stats.high} high · ${report.stats.medium} medium · ${report.stats.low} low`,
    `Session: ${open} open · ${reviewed} reviewed · ${ignored} ignored`,
    `Files analyzed: ${report.stats.analyzedFiles}${report.reviewScope?.truncated ? ' (truncated scope)' : ''}`,
  ].join('\n');
}

/**
 * Export a complete markdown review artifact for Copy Full Review / Export Markdown.
 */
export function formatPrReviewMarkdown(
  report: PRReviewReport,
  options: FormatPrReviewMarkdownOptions = {},
): string {
  const dispositions = resolveDispositionMap(options.dispositions, options.resolvedIds);
  const parts: string[] = [];

  const prHeading = report.pullRequest.title
    ? `PR #${report.pullRequest.number}: ${report.pullRequest.title}`
    : `PR #${report.pullRequest.number}`;

  parts.push(`# Review Report — ${report.repository.owner}/${report.repository.name}`);
  parts.push('');
  parts.push(prHeading);
  parts.push(`Risk level: **${report.riskLevel.toUpperCase()}**`);
  parts.push('');

  if (options.includeHandoffSummary !== false) {
    parts.push('## Handoff summary');
    parts.push(buildPrReviewHandoffSummary(report, dispositions));
    parts.push('');
  }

  parts.push('## Overview');
  parts.push(report.overview);
  parts.push('');

  parts.push('## Stats');
  parts.push(
    [
      `- Analyzed files: ${report.stats.analyzedFiles}`,
      `- Findings: ${report.stats.findings}`,
      `- High: ${report.stats.high}`,
      `- Medium: ${report.stats.medium}`,
      `- Low: ${report.stats.low}`,
      report.reviewScope?.truncated ? '- Scope: truncated (not all files loaded)' : null,
    ]
      .filter(Boolean)
      .join('\n'),
  );
  parts.push('');

  parts.push('## Risk Findings');
  if (report.findings.length === 0) {
    parts.push('_No material findings._');
  } else {
    for (const finding of report.findings) {
      parts.push(formatFinding(finding, dispositions));
    }
  }
  parts.push('');
  parts.push('_Generated by Project X — read-only review handoff. Not posted to GitHub._');

  return `${parts.join('\n').trim()}\n`;
}

/**
 * Clipboard-ready PR comment draft for manual paste (Day 10 handoff — no GitHub write).
 */
export function buildPrReviewCommentDraft(
  report: PRReviewReport,
  dispositions: PrFindingDispositionMap = {},
): string {
  const openFindings = report.findings.filter((finding) => !dispositions[finding.id]);
  const reviewedCount = report.findings.filter((f) => dispositions[f.id] === 'reviewed').length;
  const ignoredCount = report.findings.filter((f) => dispositions[f.id] === 'ignored').length;

  const lines: string[] = [
    `### Project X review — ${report.repository.owner}/${report.repository.name} #${report.pullRequest.number}`,
    '',
    `**Risk:** ${report.riskLevel.toUpperCase()}`,
    '',
    report.overview,
    '',
  ];

  if (openFindings.length > 0) {
    lines.push('**Open findings**');
    for (const finding of openFindings) {
      const path = finding.filePath ? `\`${finding.filePath}\`` : 'unspecified file';
      lines.push(
        `- **[${severityLabel(finding.severity)}]** ${path} — ${finding.title}${finding.why ? ` (${finding.why})` : ''}`,
      );
    }
    lines.push('');
  }

  if (reviewedCount > 0 || ignoredCount > 0) {
    lines.push(
      `_Session: ${reviewedCount} marked reviewed · ${ignoredCount} ignored · not posted by Project X._`,
    );
  } else {
    lines.push(
      '_Generated by Project X. Paste manually or use Post to GitHub from the extension._',
    );
  }

  return `${lines.join('\n').trim()}\n`;
}
