import type { PRReviewFinding, PRReviewReport } from '@project-x/types';

export type FormatPrReviewMarkdownOptions = {
  /** Finding ids marked resolved in this session. */
  resolvedIds?: ReadonlySet<string>;
  /** Include a short handoff blurb at the top. */
  includeHandoffSummary?: boolean;
};

function severityLabel(severity: PRReviewFinding['severity']): string {
  return severity.toUpperCase();
}

function formatFinding(
  finding: PRReviewFinding,
  resolvedIds: ReadonlySet<string> | undefined,
): string {
  const status = resolvedIds?.has(finding.id) ? 'resolved' : 'open';
  const path = finding.filePath ? `\`${finding.filePath}\`` : '_unspecified file_';
  const why = finding.why ? `\n   Why: ${finding.why}` : '';
  return `${finding.index}. **[${severityLabel(finding.severity)}]** ${path} — ${finding.title} (${status})${why}`;
}

/**
 * Client-side review handoff summary (no extra model call).
 */
export function buildPrReviewHandoffSummary(
  report: PRReviewReport,
  resolvedIds: ReadonlySet<string> = new Set(),
): string {
  const open = report.findings.filter((finding) => !resolvedIds.has(finding.id)).length;
  const resolved = report.findings.length - open;
  const prLabel = report.pullRequest.title
    ? `#${report.pullRequest.number} ${report.pullRequest.title}`
    : `#${report.pullRequest.number}`;

  return [
    `PR ${prLabel} in ${report.repository.owner}/${report.repository.name}`,
    `Overall risk: ${report.riskLevel.toUpperCase()}`,
    `Findings: ${report.stats.findings} total · ${report.stats.high} high · ${report.stats.medium} medium · ${report.stats.low} low`,
    `Session: ${open} open · ${resolved} resolved`,
    `Files analyzed: ${report.stats.analyzedFiles}${report.reviewScope?.truncated ? ' (truncated scope)' : ''}`,
  ].join('\n');
}

/**
 * Export a complete markdown review artifact for Copy Full Review / handoff.
 */
export function formatPrReviewMarkdown(
  report: PRReviewReport,
  options: FormatPrReviewMarkdownOptions = {},
): string {
  const resolvedIds = options.resolvedIds ?? new Set<string>();
  const parts: string[] = [];

  const prHeading = report.pullRequest.title
    ? `PR #${report.pullRequest.number}: ${report.pullRequest.title}`
    : `PR #${report.pullRequest.number}`;

  parts.push(`# Review Report — ${report.repository.owner}/${report.repository.name}`);
  parts.push('');
  parts.push(prHeading);
  parts.push(`Risk level: **${report.riskLevel.toUpperCase()}**`);
  parts.push('');

  if (options.includeHandoffSummary !== false) {
    parts.push('## Handoff summary');
    parts.push(buildPrReviewHandoffSummary(report, resolvedIds));
    parts.push('');
  }

  parts.push('## Overview');
  parts.push(report.overview);
  parts.push('');

  parts.push('## Stats');
  parts.push(
    [
      `- Analyzed files: ${report.stats.analyzedFiles}`,
      `- Findings: ${report.stats.findings}`,
      `- High: ${report.stats.high}`,
      `- Medium: ${report.stats.medium}`,
      `- Low: ${report.stats.low}`,
      report.reviewScope?.truncated ? '- Scope: truncated (not all files loaded)' : null,
    ]
      .filter(Boolean)
      .join('\n'),
  );
  parts.push('');

  parts.push('## Risk Findings');
  if (report.findings.length === 0) {
    parts.push('_No material findings._');
  } else {
    for (const finding of report.findings) {
      parts.push(formatFinding(finding, resolvedIds));
    }
  }
  parts.push('');
  parts.push('_Generated by Project X — read-only review handoff. Not posted to GitHub._');

  return parts.join('\n').trim() + '\n';
}
