/** Day 24 — reliability storage and payload budgets. */

export const RELIABILITY_MAX_AUDIT_EVENTS_PER_EXECUTION = 200;
export const RELIABILITY_MAX_CHECKPOINTS_PER_EXECUTION = 40;
export const RELIABILITY_MAX_TIMELINE_EVENTS = 200;
export const RELIABILITY_MAX_ARTIFACT_LINEAGE_NODES = 64;
export const RELIABILITY_MAX_PROMPT_SNAPSHOT_CHARS = 4_000;
export const RELIABILITY_MAX_SAFE_METADATA_CHARS = 2_000;
export const RELIABILITY_MAX_SNAPSHOT_GOAL_CHARS = 500;
export const RELIABILITY_MAX_FAILURE_MESSAGE_CHARS = 500;
export const RELIABILITY_MAX_LIST_EXECUTIONS = 50;
export const RELIABILITY_MAX_RETRY_ATTEMPTS = 3;
export const RELIABILITY_PROMPT_REGISTRY_NAME = 'project-x-prompt-registry';
